// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// SS_exp_Q
arma::mat SS_exp_Q(SEXP Q, double prec, bool renorm);
RcppExport SEXP _expQ2_SS_exp_Q(SEXP QSEXP, SEXP precSEXP, SEXP renormSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type Q(QSEXP);
    Rcpp::traits::input_parameter< double >::type prec(precSEXP);
    Rcpp::traits::input_parameter< bool >::type renorm(renormSEXP);
    rcpp_result_gen = Rcpp::wrap(SS_exp_Q(Q, prec, renorm));
    return rcpp_result_gen;
END_RCPP
}
// SS_v_exp_Q
arma::mat SS_v_exp_Q(const arma::mat v, SEXP Q, double prec, bool renorm, bool checks);
RcppExport SEXP _expQ2_SS_v_exp_Q(SEXP vSEXP, SEXP QSEXP, SEXP precSEXP, SEXP renormSEXP, SEXP checksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type v(vSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Q(QSEXP);
    Rcpp::traits::input_parameter< double >::type prec(precSEXP);
    Rcpp::traits::input_parameter< bool >::type renorm(renormSEXP);
    Rcpp::traits::input_parameter< bool >::type checks(checksSEXP);
    rcpp_result_gen = Rcpp::wrap(SS_v_exp_Q(v, Q, prec, renorm, checks));
    return rcpp_result_gen;
END_RCPP
}
// Unif_v_exp_Q
arma::mat Unif_v_exp_Q(const arma::mat v, SEXP Q, double prec, bool renorm, bool t2, bool checks);
RcppExport SEXP _expQ2_Unif_v_exp_Q(SEXP vSEXP, SEXP QSEXP, SEXP precSEXP, SEXP renormSEXP, SEXP t2SEXP, SEXP checksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type v(vSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Q(QSEXP);
    Rcpp::traits::input_parameter< double >::type prec(precSEXP);
    Rcpp::traits::input_parameter< bool >::type renorm(renormSEXP);
    Rcpp::traits::input_parameter< bool >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< bool >::type checks(checksSEXP);
    rcpp_result_gen = Rcpp::wrap(Unif_v_exp_Q(v, Q, prec, renorm, t2, checks));
    return rcpp_result_gen;
END_RCPP
}
// v_exp_Q
arma::mat v_exp_Q(const arma::mat v, SEXP Q, double prec, bool renorm, bool t2, bool checks);
RcppExport SEXP _expQ2_v_exp_Q(SEXP vSEXP, SEXP QSEXP, SEXP precSEXP, SEXP renormSEXP, SEXP t2SEXP, SEXP checksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type v(vSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Q(QSEXP);
    Rcpp::traits::input_parameter< double >::type prec(precSEXP);
    Rcpp::traits::input_parameter< bool >::type renorm(renormSEXP);
    Rcpp::traits::input_parameter< bool >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< bool >::type checks(checksSEXP);
    rcpp_result_gen = Rcpp::wrap(v_exp_Q(v, Q, prec, renorm, t2, checks));
    return rcpp_result_gen;
END_RCPP
}
// vT_exp_Q
arma::dvec vT_exp_Q(const arma::dvec& v, SEXP Q, double prec, bool renorm, bool t2, bool checks);
RcppExport SEXP _expQ2_vT_exp_Q(SEXP vSEXP, SEXP QSEXP, SEXP precSEXP, SEXP renormSEXP, SEXP t2SEXP, SEXP checksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::dvec& >::type v(vSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Q(QSEXP);
    Rcpp::traits::input_parameter< double >::type prec(precSEXP);
    Rcpp::traits::input_parameter< bool >::type renorm(renormSEXP);
    Rcpp::traits::input_parameter< bool >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< bool >::type checks(checksSEXP);
    rcpp_result_gen = Rcpp::wrap(vT_exp_Q(v, Q, prec, renorm, t2, checks));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_expQ2_SS_exp_Q", (DL_FUNC) &_expQ2_SS_exp_Q, 3},
    {"_expQ2_SS_v_exp_Q", (DL_FUNC) &_expQ2_SS_v_exp_Q, 5},
    {"_expQ2_Unif_v_exp_Q", (DL_FUNC) &_expQ2_Unif_v_exp_Q, 6},
    {"_expQ2_v_exp_Q", (DL_FUNC) &_expQ2_v_exp_Q, 6},
    {"_expQ2_vT_exp_Q", (DL_FUNC) &_expQ2_vT_exp_Q, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_expQ2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
